services:

  database:
    image: mysql:8.0
    container_name: r2wx-database
    restart: unless-stopped
    environment:
      MYSQL_USER: ${ENV_DBUSER}
      MYSQL_PASSWORD: ${ENV_DBPASS}
      MYSQL_DATABASE: ${ENV_DBNAME}
      MYSQL_ROOT_PASSWORD: ${ENV_DBROOT}
    ports:
      - "6306:3306"
    volumes:
      - r2wx_mysql_data:/var/lib/mysql
      - ./.database:/docker-entrypoint-initdb.d
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-P", "3306", "-u", "root", "-p${ENV_DBROOT}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - r2wx_network

volumes:
  r2wx_mysql_data:
  r2wx_pnpm_store: # Optional: for sharing pnpm global store if you mount it in Dockerfiles

networks:
  r2wx_network:
    driver: bridge